# Generated by Django 2.2.5 on 2020-02-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturent',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
