# Generated by Django 2.2.5 on 2020-02-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_resturent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturent',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
