# Generated by Django 2.2.5 on 2020-02-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200219_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturent',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
