# Generated by Django 2.2.5 on 2020-02-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200219_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('vat_no', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Resturent',
        ),
    ]
