# Generated by Django 2.2.5 on 2020-02-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200219_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Resturent',
        ),
    ]
