# Generated by Django 2.2.5 on 2020-02-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_phonenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='image/'),
        ),
    ]
