# Generated by Django 2.2.5 on 2020-02-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200223_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.BooleanField()),
                ('image', models.ImageField(default='default', upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='events',
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='food_item',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department'),
        ),
    ]
