# Generated by Django 2.2.5 on 2020-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200223_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_item',
            name='price',
            field=models.FloatField(),
        ),
    ]
