# Generated by Django 2.2.5 on 2020-02-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resturent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('image', models.ImageField(default='default', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('catagory', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('image', models.ImageField(default='default', upload_to='images/')),
                ('Resturent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.Resturent')),
            ],
        ),
    ]
