# Generated by Django 2.2.5 on 2020-02-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_Items',
            new_name='Food_Item',
        ),
    ]
