# Generated by Django 2.2.5 on 2020-02-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0002_auto_20200223_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturent',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
