# Generated by Django 2.2.5 on 2020-02-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0003_auto_20200224_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_item',
            old_name='name',
            new_name='foodname',
        ),
    ]
