# Generated by Django 2.2.5 on 2020-02-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0004_auto_20200224_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_item',
            old_name='foodname',
            new_name='name',
        ),
    ]
