# Generated by Django 2.2.5 on 2020-02-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturent',
            name='vat_no',
            field=models.CharField(max_length=30),
        ),
    ]
